[package]
name = "libai"
version = "0.2.10"
edition = "2021"
description = "AI 开发用到的一些基础数据结构"
license = "MIT OR Apache-2.0"
repository = "https://github.com/zhuchuanjing/libai"

[dependencies]
anyhow = "1.0.96"
smol_str = "0.3.2"
byteorder = "1.5"
rune = "0.13.4"
